name: Pulumi CI/CD

on:
  push:
    branches:
      - 'main'
      - 'develop'
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true  
jobs:
  pulumi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd iac
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Corrected path, since we're already in the iac directory

      - name: Install Pulumi
        uses: pulumi/actions-install-pulumi-cli@v3
        with:
          pulumi-version: 'latest'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Pulumi
        run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Pulumi Preview
        run: |
          cd iac
          pulumi stack select dev
          pulumi preview

      - name: Pulumi Update
        if: success() # Runs only if preview is successful
        run: |
          cd iac
          pulumi stack select dev
          pulumi up --yes

      - name: Notify deployment success
        run: echo "Deployment successful"
