name: Pulumi CI/CD

on:
  push:
    branches:
      - develop

jobs:
  pulumi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          cd iac
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Pulumi
        run: |
          cd iac
          curl -fsSL https://get.pulumi.com | sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Pulumi
        run: |
          cd iac
          pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Pulumi Preview
        run: |
          cd iac
          pulumi preview

      - name: Pulumi Update
        run: |
          cd iac
          pulumi up --yes

      - name: Notify deployment success
        run: echo "Deployment successful"
