name: Pulumi Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use the Python version you need

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install pulumi pulumi-aws pulumi-awsx pulumi-eks

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r iac/pulumi/requirements.txt

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Install Pulumi CLI
        run: |
          curl -fsSL https://get.pulumi.com | sh
          export PATH=$PATH:$HOME/.pulumi/bin

      - name: Login to Pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          source venv/bin/activate
          pulumi login

      - name: Configure Pulumi
        run: |
          cd iac/pulumi  # Navigate to the directory with your Pulumi files
          pulumi stack select dev  # Select the Pulumi stack (dev in this case)

      - name: Pulumi refresh
        run: |
          source venv/bin/activate
          pulumi refresh --yes --stack dev --cwd ./

      - name: Run Pulumi preview
        run: |
          cd iac/pulumi  # Ensure you are in the directory with your Pulumi files
          pulumi preview

      - name: Run Pulumi up
        run: |
          cd iac/pulumi  # Ensure you are in the directory with your Pulumi files
          pulumi up --yes

      - name: Notify deployment success
        run: echo "Deployment successful"
